# Generated by Django 4.1.5 on 2023-01-11 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_cart_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveditem',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.cart'),
        ),
    ]
