# Generated by Django 4.1.5 on 2023-01-11 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_saveditem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saveditem',
            name='cart',
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.cart'),
        ),
    ]
